# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Brian Odumo
tagline:          'A Jekyll theme'
description:      'A UWaterloo CS student with internship experience writing software.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
