# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Brian Odumo
tagline:          'A portfolio website and blog'
description:      'Software Engineer, University of Waterloo Computer Science graduate.'
url:              http://brianodumo.com
baseurl:          /

author:
  name:           'Brian Odumo'
  url:            https://twitter.com/brianodumo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
